# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Colin Weiner"
title_separator: "-"
name: "Colin Weiner"
description: "Colin Weiner's blog"
url: "https://colinweiner111.github.io"
baseurl: ""
repository: "colinweiner111/colinweiner111.github.io"
teaser: # path of default teaser image
logo: # path of logo image to display in the masthead
search: true
search_full_content: true

# Site Author
author:
  name: "Colin Weiner"
  avatar: "/assets/images/bio-photo.svg"
  bio: ""
  location: # e.g. "New York, NY"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/colinweiner111"
    # - label: "LinkedIn"
    #   icon: "fab fa-fw fa-linkedin"
    #   url: "https://linkedin.com/in/yourprofile"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/yourhandle"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/colinweiner111"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .sass-cache
  - Capfile
  - CHANGELOG
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - README
  - tmp
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
words_per_minute: 80

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
